### ISSUE TITLE
Apple Silicon (M1, M2,...) Not Supported 

### ISSUE THREAD

**Issue by patientplatypus6** [guillaume-be/rust-bert#338] opened 2023-03-16 16:49 UTC
I'm opening a new issue here because I believe that Apple M1 may not be supported. I've posted a comment on here (https://github.com/guillaume-be/rust-bert/issues/326), but this needs to be at the top of the cue, given that Apple Silicon is the latest architecture and this is the only AI tool for sentiment analysis on crates.io. (i.e. if this library works I think it's important).

The issue is claimed to be solved in the other thread. It is not.

According to the most recent documentation versions of pytorch 1.13+ work for Apple Silicon. Here is my latest architecture according to the pytorch documentation - (and a bug report submitted here https://github.com/pytorch/pytorch/issues/96959) -

```
Versions

(/Users/peterweyand/Code/rust-bert/pytorch-test/env) peterweyand@Peters-MacBook-Pro rust-bert % python collect_env.py
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.7
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.8.16 (default, Mar 1 2023, 21:18:45) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchvision==0.15.1
[conda] numpy 1.24.2 pypi_0 pypi
[conda] numpy-base 1.23.5 py38h90707a3_0
[conda] torch 2.0.0 pypi_0 pypi
[conda] torchaudio 2.0.1 pypi_0 pypi
[conda] torchvision 0.15.1 pypi_0 pypi
```

I've opened a github issue here - https://stackoverflow.com/questions/75752140/installation-of-transformer-library-not-working-in-apple-m1.

I'm excited to use this library, once an implementation for Apple Silicon is demonstrated to work.

**Comment by guillaume-be** [comment] 2023-03-21 18:01
This looks like an issue linked to the upstream dependency [tch](https://github.com/LaurentMazare/tch-rs) rather than this crate

**Comment by guillaume-be** [comment] 2023-03-21 18:02
Duplicate of https://github.com/guillaume-be/rust-bert/issues/326

**Closed by guillaume-be** 2023-03-21 18:02 UTC

**Comment by patientplatypus6** [comment] 2023-03-21 20:06
You can close this issue if you want and pass the buck on to another library - there is currently no documentation on how to build this library from scratch using an Apple Silicon chip, even after reinstalling homebrew, anaconda and python. The three files mentioned are incorrectly linked and there hasn't been any documentation on how to fix this that works.

**Comment by Raul-Cardona** [comment] 2023-07-03 05:06
@patientplatypus6 Were you able to find a solution to this issue?? Getting the exact same thing. Thanks!
