### ISSUE TITLE
Using models without vocab.txt file ?

### ISSUE THREAD

**Issue by Louis-Moreau** [guillaume-be/rust-bert#334] opened 2023-02-13 18:55 UTC
Hello,
I wanted to try some pretrained models from HuggingFace but i found out that they don't all have a vocab.txt file ( https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main ). Is there any way to generate it using the other files present or to load the vocabulary in an other file format?

**Comment by pixelspark** [comment] 2023-02-21 17:58
Same question here for a DeBertaV2 derivative. The original model supplies a `spm.model` file which appears to work (but gives incorrect results with my derivative model). 
The derivative model has neither a `vocab.txt` nor a `model.spm`, instead it has a [tokenizer_config.json](https://huggingface.co/timpal0l/mdeberta-v3-base-squad2/blob/main/tokenizer_config.json) which appears to contain a vocabulary (long list of tokens typically found in a vocab file) but then again these have weights associated with them for some reason. Not sure if conversion is feasible...

**Comment by JackKCWong** [comment] 2023-02-22 01:57
I didn't use these models before but can it not simply extract from tokenizer.json to vocab.txt? 
I think the vocab.txt just uses line num as token ids.

**Comment by pixelspark** [comment] 2023-02-22 08:06
> I didn't use these models before but can it not simply extract from tokenizer.json to vocab.txt? I think the vocab.txt just uses line num as token ids.

Well, you can try. In my case there is what looks like a list of tokens in the [tokenizer.json](https://huggingface.co/timpal0l/mdeberta-v3-base-squad2/blob/main/tokenizer.json), but I'm expecting the weights that in my case are also there to be significant (and I wouldn't know how to put those in a `vocab.txt`).

**Comment by guillaume-be** [comment] 2023-02-22 18:36
Hello,

The crate currently supports the original format used by the different models' tokenizers:
- `vocab.txt` + `merges.txt` for the WordPiece-based tokenizers (e.g. BERT, DistilBERT). The position in the vocab file indicates the token index and the order in the merges file indicate the merge priority for the wordpiece algorithm.
- `vocab.json` and `merges.txt` for the BPE-based tokenizers (RoBERTa, GPT..). Similar to above, except the token index is given as a mapping in the json file.
- `spiece.model`: sentence-piece models (BPE or unigram models) that were originally trained/used with the [sentencepiece](https://github.com/google/sentencepiece) library. These are binary `protobuf` files containing the vocabulary and merges information used for example for T5.
- `vocab.json` and `spiece.model`: combination of a vocab file for the token indices information and sentencepiece file for the merge algorithm (e..g M2M100).

It is possible to convert from/to most format if the information of the source file is richer than the destination format (for example the ordering of a `vocab.json+merges.txt` can be inferred from the scores in the sentencepiece protobuf). The logic of the tokenizer is tied to the model and should work post-conversion.

It seems that several model on the Huggingface hub now store the information in the `tokenizer.json` which is a unified format used by the [tokenizers](https://github.com/huggingface/tokenizers) library. This is currently not supported, if you would be interested I'd welcome a pull request on https://github.com/guillaume-be/rust-tokenizers so that all the tokenizers implemented could be built from `tokenizer.json` - happy to provide guidance as needed.

**Comment by heilerich** [comment] 2023-07-31 09:43
I would also like to use the multilingual MiniLM model mentioned above. Actually, I don't think converting formats is the issue here. The mentioned model, despite using the BERT architecture, seems to be using a SentencePiece Unigram Tokenizer instead of the original BERT WordPiece based tokenizer.

This tokenizer is actually supported by `rust-tokenizers` and the linked repo also has the sentencepiece model.

I think the root of the problem here is that `rust-bert` (at least the embeddings pipeline I was trying to use) is trying to load the Tokenizer based on the **model** type and not the **tokenizer** type from the configuration files. So I think the fix here would be to adjust the `TokenizerOption::from_file` method in this crate to just load the correct tokenizer from the resources (e.g. on HF) instead of just trying to load a hardcoded tokenizer depeding on the model type. Does that sound reasonable?

Maybe as a side note on this before I look into parsing the newer format configuration files: Is there a reason not to just make this crate compatible with the HF tokenizers library since it is implemented in rust by now? Seems much less work than maintaining an additional tokenizers library (i.e. `rust-tokenizers`).

**Comment by guillaume-be** [comment] 2023-07-31 17:29
Hello @heilerich ,

Most pipelines already support a constructor `new_with_tokenizer` taking a user-defined tokenizer for the usecase you are describing. I thought that this was the case for all pipelines, but this as indeed missing for `SentenceEmbeddingsModel`. I am pushing a PR (https://github.com/guillaume-be/rust-bert/pull/407) that adds it. Can you please have a look and let me know if this works for you?

Regarding your question on the support of the HF library this would be something interesting, but may require significant work.  This would need to live alongside the current `rust-tokenizer` integration (at least for a few version) while we ensure all target tokenizers are supported and no performance regression is observed. This could be done via a new variant for the `TokenizerOption` that serves as the input for current pipelines. If you are interested in starting work please feel free to start a separate issue for tracking and design.

**Comment by heilerich** [comment] 2023-08-01 20:12
Thanks for the quick addition of the `new_with_tokenizer` method. I can confirm that the method works, but sadly none of the results are as expected.

Loading the sentencepiece Model as a `TokenizerOption::Albert` works, but yields results that do not match the `AutoTokenizer` from HF. The encoded sequence starts with the `<pad>` token id (1) instead of (0) for `<s>`. The EOS token `</s>` (2) is correct. For all the other tokens indices is shifted by one (e.g. 3033 for 'test' instead of 3034). The `<pad>` token is not in the vocabulary at all.

I am not entirely sure where the HF tokenizer library is getting the information from because in addition to the `sentencepiece.bpe.model` file I am loading with rust-tokenizers a `tokenizer.json` and `unigram.json` are also present in the repository. This would probably be bad news, since both of those files are note supported by rust-tokenizers if I understand it correctly.

**Comment by guillaume-be** [comment] 2023-08-04 16:02
Hello @heilerich ,

That is correct - the tokenizer linked above uses a new `tokenizer.json` definition that was introduced a couple of years ago and that is not supported by `rust-tokenizers` (the tokenization and models API experienced a lot of changes that are difficult to reflect in a timely manner). Unfortunately trying to load other tokenizers that use `SentencePieceBpe` models does not work because they do not use the same tokenization schema/special token or rely on additional special tokens. 

The solution would indeed be to use the Huggingface tokenizer crate. Note however that it seems the Rust implementation of the tokenizers does not include the full encoding operation. For example the following:
```rust
use std::path::PathBuf;
use tokenizers::tokenizer::{Result, Tokenizer};

fn main() -> Result<()> {
    let tokenizer_file_path = PathBuf::from("path/to/tokenizer.json");
    let tokenizer = Tokenizer::from_file(tokenizer_file_path)?;
    let output = tokenizer.encode("Hey there!", false)?;
    println!("{output:?}");
    Ok(())
}
```
Does not seem to include the full encoding (e.g. addition of special tokens at the beginning and end of the sequences). This logic is handled at the Python level in the class-specific tokenizers (e.g. `BertTokenizerFast`) unless I am missing something.

**Comment by guillaume-be** [comment] 2023-08-12 09:06
@heilerich , @Louis-Moreau @pixelspark I have implemented an experimental support for the Tokenizers crate on https://github.com/guillaume-be/rust-bert/pull/408. Can you please try this out and let me know if this works for you?

The integration is made via a new variant in the `TokenizerOption` that can be loaded in pipeline's `new_with_tokenizer`:
```rust

extern crate anyhow;

use rust_bert::pipelines::common::{ModelType, TokenizerOption};
use rust_bert::pipelines::text_generation::{TextGenerationConfig, TextGenerationModel};
use rust_bert::resources::{RemoteResource, ResourceProvider};
use std::fs::File;
use std::io::Write;
use tempfile::TempDir;

fn main() -> anyhow::Result<()> {
    //    Set-up model
    let generate_config = TextGenerationConfig {
        model_type: ModelType::GPT2,
        max_length: Some(30),
        do_sample: false,
        num_beams: 1,
        temperature: 1.0,
        num_return_sequences: 1,
        ..Default::default()
    };

    // Create tokenizer
    let tmp_dir = TempDir::new()?;
    let special_token_map_path = tmp_dir.path().join("special_token_map.json");
    let mut tmp_file = File::create(&special_token_map_path)?;
    writeln!(
        tmp_file,
        r#"{{"bos_token": "<|endoftext|>", "eos_token": "<|endoftext|>", "unk_token": "<|endoftext|>"}}"#
    )?;

    let tokenizer_path = RemoteResource::from_pretrained((
        "gpt2/tokenizer",
        "https://huggingface.co/gpt2/resolve/main/tokenizer.json",
    ))
    .get_local_path()?;
    let tokenizer =
        TokenizerOption::from_hf_tokenizer_file(tokenizer_path, special_token_map_path)?;

    let model = TextGenerationModel::new_with_tokenizer(generate_config, tokenizer)?;

    let input_context = "The dog";
    // let second_input_context = "The cat was";
    let output = model.generate(&[input_context], None);

    for sentence in output {
        println!("{sentence:?}");
    }
    Ok(())
}
```

**Comment by guillaume-be** [comment] 2023-08-27 11:25
Fixed via https://github.com/guillaume-be/rust-bert/pull/408

**Closed by guillaume-be** 2023-08-27 11:25 UTC
