### ISSUE TITLE
Panic on `sequence_history.drain` conversation.rs

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [guillaume-be/rust-bert#85] opened 2020-10-13 03:19 UTC
So I have an odd one. I am writing a small chat bot using the conversation model. All is good for the first 3 responses. I write and the bot responds in less than a second. However, always on the 4th response it takes a long time to respond and then panics at:

```
   9: std::panicking::default_hook                                                                                                                                         [35/22742]
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
  13: alloc::vec::Vec<T>::drain::start_assert_failed
             at src/libcore/../stdarch/crates/core_arch/src/macros.rs:403
  14: alloc::vec::Vec<T>::drain
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/liballoc/vec.rs:1335
  15: rust_bert::pipelines::conversation::ConversationModel::clean_padding_indices
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.10.0/src/pipelines/conversation.rs:720
  16: rust_bert::pipelines::conversation::ConversationModel::generate_responses
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.10.0/src/pipelines/conversation.rs:678
```

Which is on sequence_history.drain

```rust
fn clean_padding_indices(&self, model_output: &mut Vec<Vec<i64>>) -> Vec<(usize, usize)> {
        // In case inputs are sent as batch, this cleans the padding indices in the history for shorter outputs
        let pad_token = self.model.get_pad_id().unwrap_or(self.eos_token_id);
        let mut removed_tokens = Vec::with_capacity(model_output.len());
        for sequence_history in model_output {
            let index_end = sequence_history
                .iter()
                .rev()
                .position(|&r| r != pad_token)
                .unwrap();
            let index_start = sequence_history
                .iter()
                .position(|&r| r != pad_token)
                .unwrap();
            sequence_history.drain(sequence_history.len() - index_end + 1..); // <- PANICS HERE
            sequence_history.drain(..index_start);
            removed_tokens.push((index_start, index_end));
        }
        removed_tokens
    }
```

Some advice would be appreciate, can probably clone and compile myself if you want me to do any testing.

Im not sure where this is coming from and why it is always the 4th response....

**Comment by guillaume-be** [comment] 2020-10-13 05:27
Hello,

Thank you for raising this. I am unfortunately unable to reproduce the error for a multi-turn conversation (This [example](https://gist.github.com/guillaume-be/82284220681acf410cc7cb9b6844c371) compiles and executes fine for me). The answers generated are random meaning it may cause issues with reproducibility, but you mentioned that you encounter a systematic error on the 4th round.

Could you please share the example that fails for you?

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 06:33
Ive done a bit more digging and it may be my model.

I've fine tuned the model using some old data i had from a chat bot I made ages ago and then used the convert_tensor to make the ot file (following your python scripts). Not sure why occurs systemically after 3 turns of good output or why it panics. If the model fails I expect a libray to error rather than panic. 

I tried running with the default model instead and that runs for a few turns then starts giving me blank replies after about 6-7 replies. So I think there is something going on.

Perhaps it's the multithreading I'm using.

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 06:36
I will clone your repo and do a local build with some trade messages around the panic to see if I can see the state of the model.

**Comment by guillaume-be** [comment] 2020-10-13 06:48
I managed to find an example that can reproduce the error. This was caused by a bug in the greedy decoding for generation models, and was not specific to conversations. This was causing the output to be truncated before the `eos` token at the end, causing the conversation pipeline to fail in the absence of a trailing `eos`.

I am pushing some changes that should fix this (https://github.com/guillaume-be/rust-bert/pull/86).
Thank you very much for raising this.

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 07:05
I see I will add this

```toml
rust-bert = { git = "https://github.com/guillaume-be/rust-bert", branch = "fix_greedy_generation" }
```

To my cargo.toml and see if it fixes it

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 07:59
Unfortuatly I still get the panic in the same place.

```
  12: core::panicking::panic_fmt
  13: alloc::vec::Vec<T>::drain::start_assert_failed
             at src/libcore/../stdarch/crates/core_arch/src/macros.rs:403
  14: alloc::vec::Vec<T>::drain
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/liballoc/vec.rs:1335
  15: rust_bert::pipelines::conversation::ConversationModel::clean_padding_indices
             at ~/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/989bcec/src/pipelines/conversation.rs:720
  16: rust_bert::pipelines::conversation::ConversationModel::generate_responses
             at ~/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/989bcec/src/pipelines/conversation.rs:678
```

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 08:41
So I have a local build with these changes

```rust
fn clean_padding_indices(&self, model_output: &mut Vec<Vec<i64>>) -> Vec<(usize, usize)> {
    // In case inputs are sent as batch, this cleans the padding indices in the history for shorter outputs
    trace!("Module Out: {:?}", model_output);
    let pad_token = self.model.get_pad_id().unwrap_or(self.eos_token_id);
    let mut removed_tokens = Vec::with_capacity(model_output.len());
    for sequence_history in model_output {
        let index_end = sequence_history
            .iter()
            .rev()
            .position(|&r| r != pad_token)
            .unwrap();
        let index_start = sequence_history
            .iter()
            .position(|&r| r != pad_token)
            .unwrap();
        trace!("index_start: {:?}", index_start);
        trace!("index_end: {:?}", index_end);
        sequence_history.drain(sequence_history.len() - index_end + 1..);
        sequence_history.drain(..index_start);
        removed_tokens.push((index_start, index_end));
    }
    removed_tokens
}
```

Basically just some prints

Working output for the model prints this

```
RACE rust_bert::pipelines::conversation > Module Out: [[15496, 7764, 50256, 40, 716, 7764, 13, 50256, 10995, 1309, 423, 617, 1257, 50256, 5756, 514, 8960, 13, 50256, 2504, 318, 92
2, 1165, 50256, 40, 716, 845, 4451, 13, 50256, 1639, 460, 307, 895, 283, 50256, 5211, 345, 588, 284, 1561, 546, 5536, 30, 50256]]
 TRACE rust_bert::pipelines::conversation > index_start: 0
 TRACE rust_bert::pipelines::conversation > index_end: 1
```

Panicing out this:

```
 TRACE rust_bert::pipelines::conversation > Module Out: [[15496, 7764, 50256, 40, 716, 7764, 13, 50256, 10995, 1309, 423, 617, 1257, 50256, 5756, 514, 8960, 13, 50256, 2504, 318, 92
2, 1165, 50256, 40, 716, 845, 4451, 13, 50256, 1639, 460, 307, 895, 283, 50256, 5211, 345, 588, 284, 1561, 546, 5536, 30, 50256, 22975, 318, 523, 4998, 50256, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
 TRACE rust_bert::pipelines::conversation > index_start: 0
 TRACE rust_bert::pipelines::conversation > index_end: 0
```

The reason it panics I think is that start and end are zero. Not sure why unless I delve deeper into the inner workings

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 08:43
It seems to be an exact copy of before but with zero pads... hmm  I wonder why

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 08:57
The pad character is 50256 I wonder why it could not find it

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 09:09
Ok so this happens. There are odd zeros at the end that are not the pad character. This means that the end comes up as 0 rather than any posistive number. This makes the drain go out of bounds and panic. The real question is why are there all those zeros

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 10:08
Ok so looking deeper into the code it seems that it is looping in `generate_no_beam_search` and always adding token zero until it reaches `gen_opt.max_length` and never adds a pad character to finish the string. Maybe the character should be added after max_length is reached?

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 19:06
Yes when I got the token sequence of all zeros I realised it the model was not generating correctly.

I believe My padding sequence is the same as the base model since I load it from base model without explicitly setting it. So I think there is something else mistaken in it. But I will have a check to be sure.

Thanks for the heads up.

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 19:38
For anyone else that comes here: So I was using `tokenizer.pad_token_id` but it seems that I should have been using `tokenizer.eos_token_id`. Thanks for the heads up on the issue :). Now to retrain.

**Comment by guillaume-be** [comment] 2020-10-13 19:42
You might be able to get away without retraining if you remove `pad_token_id` from your configuration. The padding would then default to `eos_token_id`. Worth a try maybe?

**Comment by QuantumEntangledAndy** [comment] 2020-10-14 00:02
I think its to do with how I did the padding in the training rather than the pad_token_id in the config. So I will just retrain.

**Comment by QuantumEntangledAndy** [comment] 2020-10-14 00:30
Anyways I have tried out latest code on the branch and it no longer panics! It does give me my all zero output but thats a different issue. Please close this when you merge the PR.

**Comment by guillaume-be** [comment] 2020-10-14 14:12
fixed with https://github.com/guillaume-be/rust-bert/pull/86

**Closed by guillaume-be** 2020-10-14 14:12 UTC
